### ISSUE TITLE
Suchleiste

### ISSUE THREAD

**Issue by arnese** [okfde/offeneregister.de#2]
Feedback per Mail: "Die Seite ist schon sehr gut, aber mir fehlt noch eine offensichtliche Möglichkeit nach Handelsregisterdaten zu suchen. Oben wird primär auf den Download verlinkt, dabei brauche ich ja gar nicht alle Daten, sonder möchte, z.B. nur nach einer Firma suchen. Könnte man oben auf die Webseite noch eine Suchleiste einbinden?"

**Comment by stefanw** [comment]
Wir sind leider kein Informationsservice, sondern eine Datenkampagne, daher können wir den angefragten Umfang nicht leisten.
